import type { Annotation, Chapter } from '../types';
import { ANNOTATION_TYPES, ANNOTATION_LABELS } from '../types';

function download(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { URL.revokeObjectURL(url); document.body.removeChild(a); }, 1000);
}

export function exportRevisionPacket(title: string, id: string, annotations: Annotation[], chapters: Chapter[]): void {
  if (!annotations.length) return;
  const sorted = [...annotations].sort((a, b) => (a.chapterIndex - b.chapterIndex) || (a.createdAt - b.createdAt));
  const counts: Record<string, number> = {};
  ANNOTATION_TYPES.forEach(t => { counts[t] = annotations.filter(a => a.type === t).length; });
  const summaryParts = ANNOTATION_TYPES.filter(t => counts[t] > 0).map(t => `${counts[t]} ${ANNOTATION_LABELS[t].toLowerCase()}${counts[t] !== 1 ? 's' : ''}`);
  const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
  const lines: string[] = [];
  lines.push(`# Revision Packet — ${title}`);
  lines.push(`\n*Generated ${date}*`);
  lines.push(`\n**${annotations.length} annotation${annotations.length !== 1 ? 's' : ''}** across ${chapters.length} chapters: ${summaryParts.join(', ')}\n`);
  lines.push('---\n');
  lines.push('## By Chapter\n');
  const byChapter: Record<number, { title: string; items: Annotation[] }> = {};
  sorted.forEach(ann => {
    const key = ann.chapterIndex || 0;
    if (!byChapter[key]) byChapter[key] = { title: ann.chapterTitle, items: [] };
    byChapter[key].items.push(ann);
  });
  Object.keys(byChapter).sort((a, b) => +a - +b).forEach(key => {
    const ch = byChapter[+key];
    lines.push((ch.title ? `### Chapter ${String(key).padStart(2, '0')} — ${ch.title}` : '### Opening') + '\n');
    ch.items.forEach(ann => {
      const icon = ({ highlight:'🟡', note:'⚪', bookmark:'🔵', question:'🔴', continuity:'🟢', structural:'🟠' } as Record<string,string>)[ann.type] ?? '•';
      lines.push(`${icon} **${ANNOTATION_LABELS[ann.type]}**`);
      if (ann.quote) lines.push(`> "${ann.quote}"`);
      if (ann.note) lines.push(`\n${ann.note}`);
      lines.push('');
    });
  });
  lines.push('---\n');
  lines.push('## By Type\n');
  ANNOTATION_TYPES.forEach(type => {
    const typed = sorted.filter(a => a.type === type);
    if (!typed.length) return;
    lines.push(`### ${ANNOTATION_LABELS[type]}s (${typed.length})\n`);
    typed.forEach(ann => {
      const loc = ann.chapterTitle ? `Ch. ${String(ann.chapterIndex).padStart(2, '0')}` : '';
      if (ann.quote) lines.push(`- ${loc ? `[${loc}] ` : ''}"${ann.quote}"${ann.note ? `\n  *${ann.note}*` : ''}`);
      else if (ann.note) lines.push(`- ${loc ? `[${loc}] ` : ''}${ann.note}`);
    });
    lines.push('');
  });
  lines.push('---\n');
  lines.push(`*${title} — revision packet generated by Vellibris*`);
  download(lines.join('\n'), `revision-packet-${id}-${new Date().toISOString().slice(0, 10)}.md`, 'text/markdown;charset=utf-8');
}
