// ─── Revision Log Export ──────────────────────────────────────────────────────
// Turns the durable trail of author Edits into a human-readable before/after
// log, grouped by chapter. This is the near-free payoff of modelling edits as
// first-class objects (vs. mutating source in place): the same structured data
// later feeds version-snapshot diffs (Phase 8) and the AI interpretation layer
// (Phase 9) without recomputation.
//
// Pure string assembly + one DOM call to trigger the download — the formatting
// is testable without a browser (see buildRevisionLogMarkdown).

import type { Edit } from '../types';

function download(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { URL.revokeObjectURL(url); document.body.removeChild(a); }, 1000);
}

/** Assemble the revision-log markdown for a set of edits. Pure: no DOM. */
export function buildRevisionLogMarkdown(title: string, edits: Edit[]): string {
  const sorted = [...edits].sort(
    (a, b) => (a.chapterIndex - b.chapterIndex) || (a.createdAt - b.createdAt),
  );
  const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

  const lines: string[] = [];
  lines.push(`# Revision Log — ${title}`);
  lines.push(`\n*Generated ${date}*`);
  lines.push(`\n**${edits.length} edit${edits.length !== 1 ? 's' : ''}**\n`);
  lines.push('---\n');

  const byChapter = new Map<number, { title: string; items: Edit[] }>();
  sorted.forEach(e => {
    const key = e.chapterIndex || 0;
    const group = byChapter.get(key) ?? { title: e.chapterTitle, items: [] };
    group.items.push(e);
    byChapter.set(key, group);
  });

  [...byChapter.keys()].sort((a, b) => a - b).forEach(key => {
    const ch = byChapter.get(key)!;
    lines.push((ch.title ? `## Chapter ${String(key).padStart(2, '0')} — ${ch.title}` : '## Opening') + '\n');
    ch.items.forEach(e => {
      lines.push('**Before:**');
      lines.push(`> ${e.originalText.trim() || '(empty)'}\n`);
      lines.push('**After:**');
      lines.push(`> ${e.replacementText.trim() || '(empty)'}\n`);
      lines.push('---\n');
    });
  });

  lines.push(`*${title} — revision log generated by Vellibris*`);
  return lines.join('\n');
}

export function exportRevisionLog(title: string, id: string, edits: Edit[]): void {
  if (!edits.length) return;
  const md = buildRevisionLogMarkdown(title, edits);
  download(md, `revision-log-${id}-${new Date().toISOString().slice(0, 10)}.md`, 'text/markdown;charset=utf-8');
}
